# Site settings

title: Open Data Science Initiative
email: 
description: > # this means to ignore newlines until "baseurl:"
  The Open Data Science Initiative aims to bring the philosophy of sharing and community resource assimilation that underpins the success of the open source software movement to the area of research software to capitalise on underlying social driver that many talented people would like to see their ideas and work being applied for the widest benefit possible.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  sods

# Build settings
markdown: kramdown
